services:
  mysql:
    image: mysql:8.4
    container_name: catalogue-tests-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalogue-tests-db
      MYSQL_USER: noodle-usr
      MYSQL_PASSWORD: noodle-usr
      TZ: Europe/Paris
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
